service: payment-manager

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  lambdaHashingVersion: 20201221
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    REGION: ${opt:region, 'localhost'}

plugins:
  - serverless-offline

package:
  patterns:
    - '!./**'
    - './node_modules/**'
    - './index-app.js'
    - './src/**'
    - '!./src/infra/migrations'

functions:
  app:
    handler: index-app.handler
    timeout: 6
    events:
      - http:
          method: POST
          path: '/customer'
          private: false
      - http:
          method: GET
          path: '/customer'
          private: false
      - http:
          method: GET
          path: '/customer/{customerId}/profile'
          private: false
      - http:
          method: GET
          path: '/customer/{customerId}/payments'
          private: false
      - http:
          method: PUT
          path: '/customer/{customerId}/profile'
          private: false
      - http:
          method: DELETE
          path: '/customer/{customerId}/profile'
          private: false
