service: payment-manager-core

custom:
  authorizer:
    name: authorizer
    arn: ${ssm:/payment-manager/${opt:stage, 'dev'}/cognito/user-pool/arn}
    identitySource: method.request.header.Authorization
    scopes:
      - aws.cognito.signin.user.admin
  serverless-offline:
    httpPort: 3001
    lambdaPort: 3002
    host: 0.0.0.0

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  lambdaHashingVersion: 20201221
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    REGION: ${opt:region, 'localhost'}
    PAYMENT_MANAGER_TABLE_NAME: ${ssm:/payment-manager/${opt:stage, 'dev'}/dynamoDB/paymanet-manager-table/name}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:*'
          Resource:
            - ${ssm:/payment-manager/${opt:stage, 'dev'}/dynamoDB/paymanet-manager-table/arn}
        - Effect: Allow
          Action:
            - 'dynamodb:*'
          Resource:
            - ${ssm:/payment-manager/${opt:stage, 'dev'}/dynamoDB/paymanet-manager-table/arn}/index/*

plugins:
  - serverless-offline

package:
  patterns:
    - '!./**'
    - './node_modules/**'
    - './index-app.js'
    - './src/**'
    - '!./src/infra/migrations'

functions:
  app:
    handler: index-app.handler
    timeout: 6
    events:
      - http:
          cors: true
          method: POST
          path: '/customer'
          authorizer: ${self:custom.authorizer}
      - http:
          cors: true
          method: GET
          path: '/customer'
          authorizer: ${self:custom.authorizer}
      - http:
          cors: true
          method: GET
          path: '/customer/{customerId}/profile'
          authorizer: ${self:custom.authorizer}
      - http:
          cors: true
          method: PUT
          path: '/customer/{customerId}/profile'
          authorizer: ${self:custom.authorizer}
      - http:
          cors: true
          method: DELETE
          path: '/customer/{customerId}/profile'
          authorizer: ${self:custom.authorizer}
      - http:
          cors: true
          method: GET
          path: '/customer/{customerId}/payments'
          authorizer: ${self:custom.authorizer}
      - http:
          cors: true
          method: POST
          path: '/customer/{customerId}/payments'
          authorizer: ${self:custom.authorizer}
      - http:
          cors: true
          method: POST
          path: '/plan'
          authorizer: ${self:custom.authorizer}
      - http:
          cors: true
          method: GET
          path: '/plan'
          authorizer: ${self:custom.authorizer}
      - http:
          cors: true
          method: GET
          path: '/plan/{planId}'
          authorizer: ${self:custom.authorizer}
      - http:
          cors: true
          method: PUT
          path: '/plan/{planId}'
          authorizer: ${self:custom.authorizer}
      - http:
          cors: true
          method: DELETE
          path: '/plan/{planId}'
          authorizer: ${self:custom.authorizer}
